version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'Logging into Amazon ECR'
      - sudo aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPO
  build:
    on-failure: ABORT
    commands:
      - sudo docker build -t $IMAGE .
      - sudo docker tag $IMAGE:$IMAGE_TAG $REPO/$IMAGE:$IMAGE_TAG
  post_build:
    on-failure: ABORT
    commands:
      - sudo docker images ls -a
      - sudo docker push $REPO/$IMAGE:$IMAGE_TAG